### ISSUE TITLE
modularization support? 

### ISSUE THREAD

**Issue by miduch** [xmartlabs/gong#186]
is there any plan for modularization support (refactor template into separate modules)? 

Thanks!

**Comment by f7deleon** [comment]
Can you be more specific about modularization? Gong was built with the idea to be a foundation to build upon but in so it has to be capable to adapt to the different needs that a project can have. By modularizing, you will be left with a static core of modules, I don't think that suits the flexibility we want.

**Comment by miduch** [comment]
please have a look at Joe Birch's following example
https://github.com/hitherejoe/minimise/tree/main/platform_android

**Comment by f7deleon** [comment]
I don't think it would be a bad idea but I think it is a matter of preference. We have tried modularization in the past and we didn't get that many advantages out of it, furthermore, it caused slow compilation times. I think this approach is more suitable for kotlin multiplatform projects like the example that you link to rather than native ones.

**Comment by miduch** [comment]
"it is a matter of preference" ... agree
